/**
 * Stable launcher generator (`src/setup/launcher.ts`).
 *
 * Why this exists: GUI clients (like Codex desktop or launchd-spawned Claude Code)
 * inherit a stripped PATH (`/usr/bin:/bin`) that omits Node version manager
 * directories (fnm, nvm, volta, Homebrew). Registering a bare command name or a
 * transient multishell path breaks either immediately or on the next Node upgrade.
 * Writing a single POSIX sh script to `<stateHome>/bin/agy-worker-mcp` allows every
 * client to register one immutable absolute path that resolves Node and the server
 * package entry point dynamically at spawn time.
 */

import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { packageRoot, stateHome } from '../contract/paths.js'

export interface LauncherOptions {
  /** Target state directory; defaults to stateHome() (respects AGY_WORKER_HOME). */
  stateHomeDir?: string
  /** The Node binary path recorded at install time as the first fallback. */
  recordedNode?: string
  /** The server entry point recorded at install time as the first fallback. */
  recordedServer?: string
  /** Package version string stamped into `<stateHome>/bin/.launcher-version`. */
  version?: string
}

export interface LauncherWriteResult {
  launcherPath: string
  versionPath: string
  scriptContent: string
}

function readPackageVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(join(packageRoot(), 'package.json'), 'utf8')) as { version?: string }
    return pkg.version ?? '0.0.0'
  } catch {
    return '0.0.0'
  }
}

/**
 * Single-quote a path for the generated script. These paths come from
 * `process.execPath` and the package root, not from user input — but they are
 * interpolated into a shell script, and a directory name containing `$` or a
 * double quote would otherwise be expanded rather than used.
 */
function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`
}

/**
 * Render the POSIX sh launcher script.
 *
 * Resolves Node and the MCP server at spawn time rather than install time, so
 * that upgrades to Node, fnm multishell changes, or package location changes
 * do not require re-registering clients.
 */
export function generateLauncherScript(options?: {
  recordedNode?: string
  recordedServer?: string
}): string {
  const recordedNode = shellQuote(options?.recordedNode ?? process.execPath)
  const recordedServer = shellQuote(options?.recordedServer ?? join(packageRoot(), 'dist', 'server.js'))

  return `#!/bin/sh
# Generated by agy-worker-setup. Resolves Node and agy-worker-mcp at spawn time.

RECORDED_NODE=${recordedNode}
RECORDED_SERVER=${recordedServer}

NODE=""

# 1. Resolve Node: explicit override -> recorded path -> current PATH -> version managers -> system
if [ -n "$AGY_WORKER_NODE" ] && [ -x "$AGY_WORKER_NODE" ]; then
  NODE="$AGY_WORKER_NODE"
elif [ -n "$RECORDED_NODE" ] && [ -x "$RECORDED_NODE" ]; then
  NODE="$RECORDED_NODE"
elif command -v node >/dev/null 2>&1; then
  CMD_NODE="$(command -v node)"
  if [ -x "$CMD_NODE" ]; then
    NODE="$CMD_NODE"
  fi
fi

# Version-manager directories are globbed, and a glob sorts lexicographically:
# "v9" sorts after "v22", so taking the last match would pick the oldest Node on
# a machine that still has a v9 lying around. Collect the matches and take the
# highest version instead, falling back to glob order where sort has no -V.
# The glob halves are deliberately outside the quotes so they expand, while
# "$HOME" stays quoted for home directories containing spaces.
if [ -z "$NODE" ]; then
  CANDIDATES=""
  for candidate in \
    "$HOME"/.local/share/fnm/node-versions/*/installation/bin/node \
    "$HOME"/.nvm/versions/node/*/bin/node \
    "$HOME"/.volta/tools/image/node/*/bin/node
  do
    if [ -x "$candidate" ]; then
      CANDIDATES="$CANDIDATES$candidate
"
    fi
  done
  if [ -n "$CANDIDATES" ]; then
    NODE="$(printf '%s' "$CANDIDATES" | sort -V 2>/dev/null | tail -n 1)"
    if [ -z "$NODE" ]; then
      NODE="$(printf '%s' "$CANDIDATES" | tail -n 1)"
    fi
  fi
fi

if [ -z "$NODE" ]; then
  for candidate in /opt/homebrew/bin/node /usr/local/bin/node /usr/bin/node; do
    if [ -x "$candidate" ]; then
      NODE="$candidate"
      break
    fi
  done
fi

if [ -z "$NODE" ]; then
  echo "agy-worker-mcp: node not found in \\$AGY_WORKER_NODE, recorded path ($RECORDED_NODE), PATH, or known locations ($HOME/.local/share/fnm, $HOME/.nvm, $HOME/.volta, /opt/homebrew, /usr/local, /usr/bin)" >&2
  exit 1
fi

# 2. Resolve server entry point: recorded path -> derived from resolved Node
SERVER=""
if [ -n "$RECORDED_SERVER" ] && [ -f "$RECORDED_SERVER" ]; then
  SERVER="$RECORDED_SERVER"
fi

# Parameter expansion, not dirname: the launcher must still work when PATH
# holds nothing at all, which is the failure it exists to survive.
NODE_DIR="\${NODE%/*}"
DERIVED_SERVER="$NODE_DIR/../lib/node_modules/agy-worker-mcp/dist/server.js"

if [ -z "$SERVER" ]; then
  if [ -f "$DERIVED_SERVER" ]; then
    SERVER="$DERIVED_SERVER"
  fi
fi

if [ -z "$SERVER" ]; then
  echo "agy-worker-mcp: server not found at recorded path ($RECORDED_SERVER) or derived from node ($DERIVED_SERVER)" >&2
  exit 1
fi

# 3. Prepend ~/.local/bin and Node's bin directory so spawned subprocesses find agy and node
PATH="$HOME/.local/bin:$NODE_DIR:$PATH"
export PATH

# 4. Hand off execution
exec "$NODE" "$SERVER" "$@"
`
}

/**
 * Write the launcher script to `<stateHome>/bin/agy-worker-mcp` with mode 0755
 * and `.launcher-version` containing the package version that generated it.
 */
export function writeLauncher(options?: LauncherOptions): LauncherWriteResult {
  const stateHomeDir = options?.stateHomeDir ?? stateHome()
  const binDir = join(stateHomeDir, 'bin')
  mkdirSync(binDir, { recursive: true, mode: 0o755 })

  const launcherPath = join(binDir, 'agy-worker-mcp')
  const versionPath = join(binDir, '.launcher-version')

  const scriptContent = generateLauncherScript({
    recordedNode: options?.recordedNode,
    recordedServer: options?.recordedServer,
  })

  writeFileSync(launcherPath, scriptContent, { mode: 0o755 })
  chmodSync(launcherPath, 0o755)

  const version = options?.version ?? readPackageVersion()
  writeFileSync(versionPath, `${version}\n`, { mode: 0o644 })

  return {
    launcherPath,
    versionPath,
    scriptContent,
  }
}
